apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: sleep
spec:
  template:
    metadata:
      labels:
        app: sleep
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 300"] # 5 min

# This job exists to give enough time for cert-manager to
# fully start, create all the certs, inject the ca bundle
# into the various locations, etc. All before we call
# cert-manager to do things for later applications.
# The cmctl tool does exist, but there is not docker container
# for me to run it and i don't want to build my own container
# just for that tool. so a blind 5 minute wait it is.
