apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: sleep
spec:
  template:
    metadata:
      labels:
        app: sleep
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 180"] # 3 min
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

# This job exists to give enough time for envoy gateway to install
# and set up its certificates, etc. after this sleep we will set up the envoy proxy
# with the settings we want.
