apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-again
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "7"
  labels:
    app: sleep
spec:
  template:
    metadata:
      labels:
        app: sleep
    spec:
      restartPolicy: Never
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 180"] # 3 min

# This job exists to give enough time for the envoy proxy
# we defined to do all the things it needs to do before
# we start creating all the gateway api resources.
