apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: all-pools
spec:
  ipAddressPools:
    - development-network-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talosworker00
    - matchLabels:
        kubernetes.io/hostname: talosworker01
    - matchLabels:
        kubernetes.io/hostname: talosworker02
